<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="description" content="Welcome to the most extraordinary hotel in Boston Massachusetts">
  <meta name="keywords" content="hotel,boston hotel,new england hotel">
  <link rel="stylesheet" href="css/style.css">
  <title>Hotel BT | About</title>
</head>
<body>
  <header>
    <nav id="navbar">
      <div class="container">
        <h1 class="logo"><a href="index.php">BBMS</a></h1>
        <ul>
          <li><a href="index.php">Home</a></li>
          <li><a class="current" href="about.php">About</a></li>
        </ul>
      </div>
    </nav>
  </header>

  <section id="about-info" class="bg-light py-3">
    <div class="container">
      <div class="info-left">
        <h1 class="l-heading"><span class="text-primary">About</span> Blood Bank</h1>
        <p>We are a non-profitable organization which aims to provide a better and easier way to find the required blood needed at the time.</p>
        <p>Blood Bank Management System (BBMS) is a browser based system that is designed to store, process, retrieve and analyze information concerned with the administrative and inventory management within a blood bank. This project aims at maintaining all the information pertaining to blood donors, different blood groups available in each blood bank and help them manage in a better way. Aim is to provide transparency in this field, make the process of obtaining blood from a blood bank hassle free and corruption free and make the system of blood bank management effective.</p>
      </div>
      <div class="info-right">
        <img src="./img/blood4.jpg" alt="blood bank">
      </div>
    </div>
  </section>

  <div class="container">
    <br>
  <h1 class="l-heading"><span class="text-primary">Features --></span></h1>
  <p>

      - Blood Donation Camp & Camp Organiser Management.<br>
      - Donor Management - Donor Registration, Managing donor database, recording their physical and medical statistics.<br>
      - Inventory management in blood bank for storage and issuance of blood.<br>
      - Blood requisition and issuance of blood.<br>
      - Online transfer of blood from one blood bank to another.<br>
      - Discarding of expired and unsuitable blood (Less Qty., Reactive, Clotting, Hemolysis).<br>
      - Being a web based system, can be implemented throughout the state. - - Separate user accounts can be created for each blood bank.<br>
      - Patient Register/Blood Sample Receiving Register, Donor Register, Blood Issue Register and Discarded Blood report.<br>
      - Fridge Wise Stock Position and Printing of Fridge Stickers.<br>
      - List of Donors who are eligible for donation on a particular date with contact Number.<br>
      - Camp Wise Donor List and Printing of Donor Cards.<br>
</p>

</div>


</body>
</html>